services:
  # ===================================================================================================================================================================================
  backend:
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
  # ===================================================================================================================================================================================
  caddy:
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
  # ===================================================================================================================================================================================
  postgres-test:
    image: postgres:17.2
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=lunisoft
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_DB=test
    restart: unless-stopped
  # ===================================================================================================================================================================================
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOST=${APP_REDIS_HOST}
      - REDIS_PORT=${APP_REDIS_PORT}
      - REDIS_PASSWORD=GhostLexly.7
    ports:
      - "8081:8081"
